config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'

  get 'activities/index' # , protect_from_forgery :except => :index

  root 'tickets#index'

  devise_for :users
  resources :users do
    resources :tickets
  end
  
  resources :tickets do
    resources :comments
  end

  resources :activities
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, Ticket
      can :read, Comment
      can :create, Ticket
      can :create, Comment
    end
  end
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include PublicActivity::Model
  tracked only: :create, :owner => proc {|controller, model| controller.current_user} # set owner to current_user by default (check app/controllers/application_controller.rb)

  belongs_to :ticket
  belongs_to :user
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  include PublicActivity::Model
  tracked :owner => proc {|controller, model| controller.current_user} # set owner to current_user by default (check app/controllers/application_controller.rb)

  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true

  acts_as_taggable
  acts_as_taggable_on :label

  def last_update
    last_update = updated_at
    if comments.last and updated_at < comments.last.updated_at
      last_update = comments.last.updated_at 
    end
    last_update
  end

  def to_param
    "#{id}-#{title}".parameterize
  end

  def long_title
    "##{id}: #{title}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  include PublicActivity::Model

  after_create :track
  tracked only: :create, owner: :itself

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tickets
  has_many :comments

  def track
  end

  def username
    email.partition('@').first
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @activities = PublicActivity::Activity.order("created_at desc")

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Necessary include if you plan on access controller instance
  # in Procs passed to #tracked method in your models
  include PublicActivity::StoreController
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def create
    @ticket = Ticket.find(params[:ticket_id])
    @comment = @ticket.comments.create(comment_params)
    @comment.user = current_user
    @comment.user_agent = request.user_agent
    @comment.save
    redirect_to ticket_path(@ticket)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  load_and_authorize_resource
  
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index]

  # GET /tickets
  # GET /tickets.json
  def index
    if current_user.nil?
      redirect_to pages_index_url
    elsif current_user.admin?
      @tickets = Ticket.all.sort {|a,b| a.last_update <=> b.last_update}
    elsif current_user.id.to_s == params[:user_id].to_s
      @user = User.find(params[:user_id])
      @tickets = @user.tickets.sort {|a,b| a.last_update <=> b.last_update}
    elsif
      redirect_to user_tickets_path(current_user.id)
    end
    @opened_tickets = @tickets.select { |ticket| ticket.closed == false }
    @closed_tickets = @tickets.select { |ticket| ticket.closed == true }
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.user = current_user
    @ticket.user_agent = request.user_agent

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Le ticket a bien été créé.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Le ticket a bien été mis à jour.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Le ticket a bien été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:title, :url, :body, :closed, :tag_list, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def show
  end

  private
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/index.html.erb
<div class="page-header">
  <h2>Timeline</h2>
</div>

<div id="activities" data-url="<%= activities_url format: :js %>">
  <% @activities.each do |activity| %>
    <h5>  
      <% if activity.owner %>
        <%= link_to activity.owner.username, activity.owner %>
      <% else %>
        un utilisateur qui a depuis été supprimé
      <% end %>
      <%= render_activity activity %>
    </h5>
    <div class="text-right infos">
      <small>il y a <%= time_ago_in_words(activity.created_at.localtime) %></small>
    </div>
    <br/>
    <hr/>
    <br/><br/>
  <% end %>
</div>

app/views/activities/index.js.erb
alert("yo");
ActivityPoller.poll();

app/views/comments/_form.html.erb
<%= form_for(@comment, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @comment.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h4>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :ticket, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :ticket, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body, :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :body, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="page-header">
  <%= link_to comments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @comment, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing comment</h1>
</div>

<%= render 'form' %>

app/views/comments/index.html.erb
<div class="page-header">
  <%= link_to new_comment_path, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Comment
  <% end %>
  <h1>Listing comments</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Ticket</th>
        <th>Body</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @comments) do |comment| %>
        <td><%= comment.ticket.title %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/comments/new.html.erb
<div class="page-header">
  <%= link_to comments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New comment</h1>
</div>

<%= render 'form' %>

app/views/comments/show.html.erb
<div class="page-header">
  <%= link_to comments_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_comment_path(@comment), :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show comment</h1>
</div>

<dl class="dl-horizontal">
  <dt>Ticket:</dt>
  <dd><%= @comment.ticket %></dd>

  <dt>Body:</dt>
  <dd><%= @comment.body %></dd>

</dl>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "tikkets", "/", :class => "navbar-brand" %>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <p class="navbar-text"></p>
      <ul class="nav navbar-nav">
        <% if current_user %>
          <li class="<%= 'active' if current_page?(root_path) or current_page?(user_tickets_path(current_user))%>">
            <%= link_to 'mes tickets', user_tickets_path(current_user) %>
          </li>
        <% end %>
        <% if current_user and current_user.admin? %>
          <li class="<%= 'active' if current_page?(tickets_path) %>"><%= link_to "tous les tickets", tickets_path %></li>
          <li class="<%= 'active' if current_page?(activities_path) %>"><%= link_to 'timeline', activities_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if not user_signed_in? %>
          <li><%= link_to('connexion', new_user_session_path) %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
              <%= current_user.username %>  <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to('déconnexion', destroy_user_session_path, :method => :delete) %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>tickets</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header.html.erb' %>

  <div class="container">
    <div class="row">
      <div class="col-md-8">
        <% flash.each do |name, msg| %>
          <%= content_tag :div, :class => "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", :role => "alert" do %>
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
            <%= msg %>
          <% end %>
        <% end %>

        <%= yield %>

      </div>

      <% if content_for? :sidebar %>
        <div class="col-md-3 col-md-offset-1">
          <div class="sidebar">
            <%= yield :sidebar %>
          </div>
        </div>
      <% end %>

    </div>
  </div>


</body>
</html>

app/views/pages/index.html.erb
<div class="page-header">
  <h1>Bienvenue sur Tikkets</h1>
</div>
<h4>Vous participez au Yakathon et toute l'équipe de Yakarouler vous en remercie.</h4>
<br/><br/>
<div class="alert alert-info">
  <h4>Pour continuer, merci de créer un compte</h4>
  <br/>
  <%= link_to "S'inscrire", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/public_activity/comment/_create.html.erb
<% if activity.trackable and activity.trackable.ticket %>
  a répondu au ticket <%= link_to activity.trackable.ticket.long_title, activity.trackable.ticket %>
<% else %>
  a répondu à un ticket qui a depuis été supprimé.
<% end %>
<div class="h1 text-muted">
  <%= fa_icon "comment" %>
</div>

app/views/public_activity/ticket/_create.html.erb
<% if activity.trackable %>
  a créé le ticket <%= link_to activity.trackable.long_title, activity.trackable %>
<% else %>
  a créé un ticket qui a depuis été supprimé.
<% end %>
<div class="h1 text-muted">
  <%= fa_icon "file" %>
</div>

app/views/public_activity/ticket/_destroy.html.erb
a modifié un ticket qui a depuis été supprimé

app/views/public_activity/ticket/_update.html.erb
<% if activity.trackable %>
  a mise à jour le ticket <%= link_to activity.trackable.long_title, activity.trackable %>
<% else %>
  a mise à jour un ticket qui a depuis été supprimé.
<% end %>

<div class="h1 text-muted">
  <%= fa_icon "pencil" %>
</div>

app/views/public_activity/user/_create.html.erb
s'est inscrit
<div class="h1 text-muted">
  <%= fa_icon "user" %>
</div>

app/views/tickets/_form.html.erb
<%= form_for(@ticket, :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <% if @ticket.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@ticket.errors.count, "erreur") %> s'est produite :</h4>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user.admin? %>
    <div class="form-group">
      <%= f.label :closed, 'Ticket fermé', :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.check_box :closed, :class => "form-control" %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :title, 'Sujet', :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :url, 'Url', :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :url, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :body, 'Objet', :class => "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :body, rows: "16", :class => "form-control" %>
    </div>
  </div>
  <% if current_user.admin? %>
    <div class="form-group">
      <%= f.label :tag_list, 'Tags', :class => "col-sm-2 control-label" %>
      <div class="col-sm-10">
        <%= f.text_area :tag_list, rows: "1", :class => "form-control" %>
      </div>
    </div>
  <% end %>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<div class="page-header">
  <%= link_to tickets_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Retour
  <% end %>
  <%= link_to @ticket, :class => 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Voir le ticket
  <% end %>
  <h1>Edition d'un ticket</h1>
</div>

<%= render 'form' %>

app/views/tickets/index.html.erb
<div class="page-header">
  <h2>
    <% if current_page?(tickets_path) %>
      Tous les tickets ouverts <small>(<%= @tickets.count %>)</small>
    <% else %>
      Mes tickets ouverts <small>(<%= @opened_tickets.count %>)</small>
    <% end %>
  </h2>
</div>

<div class="text-right">
  <%= link_to new_ticket_path, :class => 'btn btn-success' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Nouveau ticket
  <% end %>
</div>

<br/>

<% if @opened_tickets.any? %>
  <div class="opened-tickets">
    <div class="container-fluid">
      <% @opened_tickets.each_with_index do |ticket, index| %>
        <div class="row <%= 'focus' if index == 0 %>">
          <div class="col-xs-10">
            <h3><%= link_to ticket.long_title, ticket %></h3>
            <% if can? :read, ticket.tags %>
              <% ticket.tags.each do |tag| %>
                <%= link_to tag, '#', class: "label label-default label-#{tag}" %>
              <% end %>
            <% end %>
            <br/><br/>
          </div>
          <div class="col-xs-2"> 
            <div class="infos text-right">
              <small>il y a <%= time_ago_in_words(ticket.last_update.localtime) %></small><br/>
              <small><%= link_to "Réponses (#{ticket.comments.count})", ticket %></small>
            </div>
          </div>    
        </div>
      <% end %>
    </div>
  </div>

<% else %>
  <div class="alert alert-info text-center">
    <h3>Il n'y a pas de ticket ouvert.</h3>
    <%= link_to new_ticket_path, :class => 'btn btn-lg btn-link' do %>
      <span class="glyphicon glyphicon-plus"></span>
      Nouveau ticket
    <% end %>
  </div>
<% end %>

<% if @closed_tickets.any? %>
  <%= content_for :sidebar do %>
    <br/><br/>
    <div class="well">
      <h4>Tickets fermés <small>(<%= @closed_tickets.count %>)</small></h4>
      <ul>
        <% @closed_tickets.each do |ticket| %>
          <li>
            <%= link_to "##{ticket.id}: #{truncate(ticket.title, length: 40)}", ticket %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/tickets/new.html.erb
<div class="page-header">
  <%= link_to tickets_path, :class => 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Retour
  <% end %>
  <h1>Nouveau ticket</h1>
</div>

<%= render 'form' %>

<%= content_for :sidebar do %>
  <br/><br/>
  <div class="alert alert-danger">
    <h4>Instructions</h4>
    <p>
      <ul>
        <li>choisir un titre clair</li>
        <li>noter l'url</li>
        <li>expliquer en détail la démarche pour reproduire</li>
      </ul>
    </p>
  </div>
  <div class="alert text-success">
    <h4>Remarque</h4>
    <p>Vous pouvez nous appeler à tout moment</p>
  </div>
<% end %>

app/views/tickets/show.html.erb
<div class="text-right">
  <% if can? :update, @ticket %>
    <%= link_to edit_ticket_path(@ticket), :class => 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-pencil"></span>
      Editer
    <% end %>
  <% end %>
</div>

<h3><%= @ticket.long_title %></h3>
<% if not @ticket.url.blank? %>
  <h5>Url : <%= auto_link(@ticket.url) %></h5>
<% end %>

<br/><br/>

<% if not @ticket.body.blank? %>
  <div class="big">
    <%= auto_link(simple_format(h(@ticket.body))) %>
    <br/>
  </div>
<% end %>

<div class="text-right infos">
  <% if can? :read, @ticket.tags %>
    <% @ticket.tags.each do |tag| %> <%= link_to tag, '#', class: "label label-default label-#{tag}" %><% end %><br/>
  <% end %>
  <small><em>il y a <%= time_ago_in_words(@ticket.created_at.localtime) %></em></small><br/>
  <small><em><%= @ticket.user.username %></em></small><br/>
    <% if current_user.admin? %>
      <small><em><%= @ticket.user_agent %></em></small>
    <% end %>
</div>

<br/>

<h3>Réponses <small>(<%= @ticket.comments.count %>)</small></h3>

<div class="row">
  <div class="col-sm-11">
    <% @ticket.comments.each do |comment| %>
      <div class="ticket-comment <%= 'focus' if comment == @ticket.comments.last %>">
        <%= auto_link(simple_format(h(comment.body))) %>
        <br/><br/>
        <div class="text-right infos">
          <small><em>il y a <%= time_ago_in_words(comment.created_at.localtime) %></em></small><br/>
          <small><em><%= comment.user.username %></em></small><br/>
          <% if current_user.admin? %>
            <small><em><%= comment.user_agent %></em></small>
          <% end %>
        </div>
      </div>
      <hr/>
    <% end %>
  </div>
</div>


<h5>Commenter :</h5>
<%= form_for([@ticket, @ticket.comments.build], :html => { :class => "form-horizontal", :role => "form" }) do |f| %>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.text_area :body, rows: "4", :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-10">
      <%= f.submit 'Commenter', :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="page-header">
  <h4><%= @user.email %></h4>
</div>